### ISSUE TITLE
iOS build

### ISSUE THREAD

**Issue by TyroneSlothrop** [io12/qemu-libretro#1]
First of all thank you so much for providing QEmu through libretro's API - this is a tremendously important intersection for preservation and portability.

Then I was following some of the errors on the latest buildbot where there are seemingly opengl related issues and just wanted to flag https://github.com/utmapp/qemu as a project that had managed to get qemu working in the backend -- hopefully there is some info therein. I'm afraid I am not C-savvy myself but I am happy to keep trying dylib builds if it helps - you have an audiance rooting for you.

**Comment by io12** [comment]
Thanks! I was planning to give up on iOS builds for now, but I can try applying my changes to UTM's fork and see if that helps.

**Comment by io12** [comment]
I managed to get something built. https://git.libretro.com/libretro/qemu-libretro/-/jobs/5794619/artifacts/raw/qemu_libretro_ios.dylib

**Comment by TyroneSlothrop** [comment]
hey was only able to test just now - I used the version on the retroarch build bot and had to assemble a little core info file so as to open the kalibri iso (using it as a benchmark), unfortunately it 'fails to open libretro core'

The logs seem to show the following missing dependencies I think:

[ERROR] Failed to open libretro core: "/private/var/containers/Bundle/Application/24F907E3-6A86-4369-8181-FFD4F3F65659/RetroArch.app/Frameworks/qemu.libretro.framework"
[ERROR] Error(s): dlopen(/private/var/containers/Bundle/Application/24F907E3-6A86-4369-8181-FFD4F3F65659/RetroArch.app/Frameworks/qemu.libretro.framework/qemu.libretro, 0x0005): Library not loaded: @rpath/libffi.7.dylib
  Referenced from: <32EDE5F9-6E3C-337E-A752-A3B96346EC5F> /private/var/containers/Bundle/Application/24F907E3-6A86-4369-8181-FFD4F3F65659/RetroArch.app/Frameworks/qemu.libretro.framework/qemu.libretro
  Reason: tried: '/private/var/containers/Bundle/Application/24F907E3-6A86-4369-8181-FFD4F3F65659/RetroArch.app/Frameworks/qemu.libretro.framework/subprojects/libffi/src/libffi.7.dylib' (no such file), '/private/var/containers/Bundle/Application/24F907E3-6A86-4369-8181-FFD4F3F65659/RetroArch.app/Frameworks/qemu.libretro.framework/subprojects/libffi/src/libffi.7.dylib' (no such file), '/usr/lib/swift/libffi.7.dylib' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/libffi.7.dylib' (no such file), '/private/var/containers/Bundle/Application/24F907E3-6A86-4369-8181-FFD4F3F65659/RetroArch.app/Frameworks/libffi.7.dylib' (no such file), '/private/var/containers/Bundle/Application/24F907E3-6A86-4369-8181-FFD4F3F65659/RetroArch.app/Frameworks/MoltenVK.framework/libffi.7.dylib' (no such file), '/usr/lib/swift/libffi.7.dylib' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/libffi.7.dylib' (no such file), '/private/var/containers/Bundle/Application/24F907E3-6A86-4369-8181-FFD4F3F65659/RetroArch.app/Frameworks/libffi.7.dylib' (no such file), '/private/var/containers/Bundle/Application/24F907E3-6A86-4369-8181-FFD4F3F65659/RetroArch.app/Frameworks/MoltenVK.framework/libffi.7.dylib' (no such file)

**Comment by TyroneSlothrop** [comment]
Solved around commit dcfe36c0de139f064669b6a3554d2c2d05716a99
